version: "3.8"

networks:
  default:
    name: ergo-explorer
  ergo-node:
    external: true

volumes:
  ergo_redis:
    external: true

services:
  # Postgresql database
  db:
    build:
      context: ./db
      args:
        EXPLORER_VERSION: 9.16.4
    environment:
      POSTGRES_DB: ergo
      POSTGRES_USER: ergo
    env_file:
      # Defines POSTGRES_PASSWORD
      - ./db/db.secret
    volumes:
      # Mapped volume for easier Postgres upgrades.
      # Make sure the path exists or edit it here.
      # See also readme_pg_upgrade.md
      - /var/lib/explorer_pg/14/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # Redis
  redis:
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server"]
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ergo_redis:/usr/local/etc/redis

  # Explorer backend chain-grabber
  grabber:
    build:
      context: ./explorer-backend-9.16.4
      dockerfile: chain-grabber.Dockerfile
    env_file:
      # Defines POSTGRES_PASSWORD
      - ./db/db.secret
    volumes:
      - ./explorer-backend.conf:/explorer-backend.conf:ro
    networks:
      - default
      - ergo-node
    command: /explorer-backend.conf
    links:
      - "db"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # Explorer API
  api:
    build:
      context: ./explorer-backend-9.16.4
      dockerfile: explorer-api.Dockerfile
    env_file:
      # Defines POSTGRES_PASSWORD
      - ./db/db.secret
    volumes:
      - ./explorer-backend.conf:/explorer-backend.conf:ro
    command: /explorer-backend.conf
    links:
      - "db"
      - "redis"
    restart: unless-stopped
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # Explorer UI
  ui:
    build:
      context: ./ui
      args:
        # Set this to the url the api should be accessed at
        API: 192.168.1.72:8080
    links:
      - "api"
    ports:
      - 3000:3000
    
